# Part 1

### 1. Identify the species and the gene that the DNA sequence belongs to:
#### Species: Bos Taurus
#### Gene: EEF1A1
### 2. Using the filters of online BLAST narrow down your search to the species Bison. Are there sequences with high similarity?
#### There are 5 sequences with high similarity, above 97% identity.
### 3. Repeat the procedure for the species Mus musculus.
#### There aren't any sequences with high similarity.
### 4. You can translate your DNA sequence to Amino Acid sequences using the online tool expasy translate. Translate your DNA sequence to Amino Acids sequence and select the results of the first frame. Go to the BLAST again and run the protein-protein version of the tool. 
#### Translated DNA sequence to Amino Acid sequence:

#### MGKEKTHINIVVIGHVDSGKSTTTGHLIYKCGGIDKRTIEKFEKEAAEMGKGSFKYAWVLDKLKAERERGITIDISLWKFETSKYYVTIIDAPGHRDFIKNMITGTSQADCAVLIVAAGVGEFEAGISKNGQTREHALLAYTLGVKQLIVGVNKMDSTEPPYSQKRYEEIVKEVSTYIKKIGYNPDTVAFVPISGWNGDNMLEPSANMPWFKGWKVTRKDGNASGTTLLEALDCILPPTRPTDKPLRLPLQDVYKIGGIGTVPVGRVETGVLKPGMVVTFAPVNVTTEVKSVEMHHEALSEALPGDNVGFNVKNVSVKDVRRGNVAGDSKNDPPMEAAGFTAQVIILNHPGQISAGYAPVLDCHTAHIACKFAELKEKIDRRSGKKLEDGPKFLKSGDAAIVDMVPGKPMCVESFSDYPPLGRFAVRDMRQTVAVGVIKAVDKKAAGAGKVTKSAQKAQKAK

### 5. Again, using the filters of online BLAST narrow down your search to the species Bison. Are there sequences with high similarity? Repeat the procedure for the species Mus musculus.
#### There is 1 sequence with high similarity compared to the species Bison, with 99,78% identity .
#### There are 6 sequences with high similarity compared to the species Mus musculus, above 99,5 % identity.

## Part 2
#### The DNA sequence of CTCF gene for 
#### homo sapiens:
http://139.91.190.186/tei/bioinformatics/exercise2/CTCF_DNA_HOMO.fna
#### and for mus musculus:
http://139.91.190.186/tei/bioinformatics/exercise2/CTCF__DNA_MUS.fna
#### The protein sequence (amino acid) of CTCF gene for 
#### homo sapiens:
http://139.91.190.186/tei/bioinformatics/exercise2/CTCF_AA_HOMO.faa
#### and for mus musculus:
http://139.91.190.186/tei/bioinformatics/exercise2/CTCF_AA_MUS.faa
##### I have saved them locally.

### Read all 4 files

In [29]:
dna_homo = 'CTCF_DNA_HOMO.fna'
f = open(dna_homo)
dna_homo_lines = f.readlines()
f.close()
#dna_homo_lines

In [30]:
dna_mus = 'CTCF__DNA_MUS.fna'
f = open(dna_mus)
dna_mus_lines = f.readlines()
f.close()
#dna_mus_lines

In [31]:
aa_homo = 'CTCF_AA_HOMO.faa'
f = open(aa_homo)
aa_homo_lines = f.readlines()
f.close()
#aa_homo_lines

In [32]:
aa_mus = 'CTCF_AA_MUS.faa'
f = open(aa_mus)
aa_mus_lines = f.readlines()
f.close()
#aa_mus_lines

### 1. Use the first 100 nucleotides from the DNA sequence of CTCF gene for human and mouse to create a Dot Matrix with k-mer k=6. 

#### Creating the DNA sequences of CTCF gene for both human and mouse.

In [33]:
sequence_dna_homo = ''
for i in dna_homo_lines[1:]:
    sequence_dna_homo += i.strip()
#sequence_dna_homo

In [34]:
sequence_dna_mus = ''
for i in dna_mus_lines[1:]:
    sequence_dna_mus += i.strip()
#sequence_dna_mus

#### Each secuence will contain 100 nucleotides

In [35]:
sequence_dna_homo=sequence_dna_homo[0:100]
sequence_dna_mus=sequence_dna_mus[0:100]

#### Define the delta function:

In [36]:
def delta(x,y):
    return 0 if x == y else 1

#### M[i,j]

In [37]:
def M(seq1,seq2,i,j,k):
    return sum(delta(x,y) for x,y in zip(seq1[i:i+k],seq2[j:j+k]))

#### Define the creation of the Dot Matrix

In [38]:
def makeMatrix(seq1,seq2,k):
    n = len(seq1)
    m = len(seq2)
    return [[M(seq1,seq2,i,j,k) for j in range(m-k+1)] for i in range(n)]

#### Plot the matrix

In [39]:
def plotMatrix(M, seq1, seq2, t=1, nonblank = chr(0x25A0), blank = ' '):
    print(' ' + seq2)
    for label,row in zip(seq1,M):
        line = ''.join(nonblank if s < t else blank for s in row)
        print(label + line)

In [40]:
def dotplot(seq1,seq2,k = 6):
    M = makeMatrix(seq1,seq2,k)
    plotMatrix(M, seq1,seq2)

In [41]:
dotplot(sequence_dna_homo,sequence_dna_mus)

 AAACCGTGCGCGGAGCTGCTTCTTTGGCGGCAGCGGCGACCAGCAGCAGCCGGTGCGGGCGCGCGGAGCCGGCCGGGGACGCCAGGTGGCCGGAGCGGTG
G                                                                                               
A                                                                                               
C                                                                                               
G                                                                                               
C                                                                                               
A                                                                                               
G                                                                                               
G                                                                                               
C                                                                                               
G                        

### 2. Use the protein sequence of CTCF gene for human and mouse to create a Dot Matrix with k-mer k=3.

#### Creating the protein sequences of CTCF gene for both human and mouse.

In [42]:
sequence_aa_homo = ''
for i in aa_homo_lines[1:]:
    sequence_aa_homo += i.strip()
#sequence_aa_homo

In [43]:
sequence_aa_mus = ''
for i in aa_mus_lines[1:]:
    sequence_aa_mus += i.strip()
#sequence_aa_mus

#### Each sequence will contain only 100 characters (if not, the dot matrix will be too big and it won't be depicted correctly)

In [44]:
sequence_aa_homo=sequence_aa_homo[0:100]
sequence_aa_mus=sequence_aa_mus[0:100]

#### Plot the dot matrix

In [45]:
def dotplot(seq1,seq2,k = 3):
    M = makeMatrix(seq1,seq2,k)
    plotMatrix(M, seq1,seq2)
dotplot(sequence_aa_homo,sequence_aa_mus)

 MEGEAVEAIVEESETFIKGKERKTYQRRREGGQEEDACHLPQNQTDGGEVVQDVNSSVQMVMMEQLDPTLLQMKTEVMEGTVAPEAEAAVDDTQIITLQV
M■                                                                            ■                    
E                                                                                                  
G                                                                                                  
D                                                                                                  
A    ■                                                                                             
V     ■                                                                                            
E      ■                                                                                           
A       ■                                                                                          
I        ■                                                                                        

## Part 3

### Using the datasets from part 2, implement your own Smith-Waterman Algorithm for global alignment of the Amino Acid sequences with the following parameters: Identical = +2, substitution = -2 and gap penalty = -1. Print the final scoring matrix and find the position of the highest value. 
####  Final scoring matrix using Smith-Waterman Algorithm:

In [46]:
import numpy as np

def matrix(a, b, match_score=2, gap_cost=1):
    H = np.zeros((len(a) + 1, len(b) + 1), np.int)

    for i in range(1, H.shape[0]):
        for j in range(1, H.shape[1]):
            match = H[i - 1, j - 1] + (match_score if a[i - 1] == b[j - 1] else - match_score)
            delete = H[i - 1, j] - gap_cost
            insert = H[i, j - 1] - gap_cost
            H[i, j] = max(match, delete, insert, 0)
    return H

print(matrix(sequence_aa_homo, sequence_aa_mus))

[[  0   0   0 ...   0   0   0]
 [  0   2   1 ...   0   0   0]
 [  0   1   4 ...   0   0   0]
 ...
 [  0   0   0 ... 192 191 190]
 [  0   0   0 ... 191 194 193]
 [  0   0   0 ... 190 193 196]]


#### Final scoring matrix (a better-looking version of the above).

In [47]:
import pandas as pd

arr_seq_aa_mus = list(sequence_aa_mus)
arr_seq_aa_mus.insert(0," ")

table = pd.DataFrame(np.array(matrix(sequence_aa_homo, sequence_aa_mus)),
                   columns=arr_seq_aa_mus)

arr_seq_aa_homo = list(sequence_aa_homo)
arr_seq_aa_homo.insert(0," ")

table.index = arr_seq_aa_homo
table

M  E  G  E  A  V   E   A   I ...     D    D    T    Q    I    I    T  \
    0  0  0  0  0  0  0   0   0   0 ...     0    0    0    0    0    0    0   
M   0  2  1  0  0  0  0   0   0   0 ...     0    0    0    0    0    0    0   
E   0  1  4  3  2  1  0   2   1   0 ...     0    0    0    0    0    0    0   
G   0  0  3  6  5  4  3   2   1   0 ...     0    0    0    0    0    0    0   
D   0  0  2  5  4  3  2   1   0   0 ...     2    2    1    0    0    0    0   
A   0  0  1  4  3  6  5   4   3   2 ...     1    1    0    0    0    0    0   
V   0  0  0  3  2  5  8   7   6   5 ...     3    2    1    0    0    0    0   
E   0  0  2  2  5  4  7  10   9   8 ...     2    1    0    0    0    0    0   
A   0  0  1  1  4  7  6   9  12  11 ...     2    1    0    0    0    0    0   
I   0  0  0  0  3  6  5   8  11  14 ...     1    0    0    0    2    2    1   
V   0  0  0  0  2  5  8   7  10  13 ...     4    3    2    1    1    1    0   
E   0  0  2  1  2  4  7  10   9  12 ...     3    2    1    0    0    0    0   
E   0  0  2  1  3  3  6   9   8  11 ...     2    1    0    0    0    0    0   
S   0  0  1  0  2  2  5   8   7  10 ...     1    0    0    0    0    0    0   
E   0  0  2  1  2  1  4   7   6   9 ...     0    0    0    0    0    0    0   
T   0  0  1  0  1  0  3   6   5   8 ...     0    0    2    1    0    0    2   
F   0  0  0  0  0  0  2   5   4   7 ...     0    0    1    0    0    0    1   
I   0  0  0  0  0  0  1   4   3   6 ...     0    0    0    0    2    2    1   
K   0  0  0  0  0  0  0   3   2   5 ...     0    0    0    0    1    1    0   
G   0  0  0  2  1  0  0   2   1   4 ...     0    0    0    0    0    0    0   
K   0  0  0  1  0  0  0   1   0   3 ...     0    0    0    0    0    0    0   
E   0  0  2  1  3  2  1   2   1   2 ...     0    0    0    0    0    0    0   
R   0  0  1  0  2  1  0   1   0   1 ...     0    0    0    0    0    0    0   
K   0  0  0  0  1  0  0   0   0   0 ...     0    0    0    0    0    0    0   
T   0  0  0  0  0  0  0   0   0   0 ...     0    0    2    1    0    0    2   
Y   0  0  0  0  0  0  0   0   0   0 ...     0    0    1    0    0    0    1   
Q   0  0  0  0  0  0  0   0   0   0 ...     0    0    0    3    2    1    0   
R   0  0  0  0  0  0  0   0   0   0 ...     0    0    0    2    1    0    0   
R   0  0  0  0  0  0  0   0   0   0 ...     0    0    0    1    0    0    0   
R   0  0  0  0  0  0  0   0   0   0 ...     0    0    0    0    0    0    0   
.. .. .. .. .. .. .. ..  ..  ..  .. ...   ...  ...  ...  ...  ...  ...  ...   
L   0  0  0  0  0  0  0   0   0   0 ...   118  117  116  115  114  113  112   
Q   0  0  0  0  0  0  0   0   0   0 ...   121  120  119  118  117  116  115   
M   0  2  1  0  0  0  0   0   0   0 ...   124  123  122  121  120  119  118   
K   0  1  0  0  0  0  0   0   0   0 ...   127  126  125  124  123  122  121   
T   0  0  0  0  0  0  0   0   0   0 ...   130  129  128  127  126  125  124   
E   0  0  2  1  2  1  0   2   1   0 ...   133  132  131  130  129  128  127   
V   0  0  1  0  1  0  3   2   1   0 ...   136  135  134  133  132  131  130   
M   0  2  1  0  0  0  2   1   0   0 ...   139  138  137  136  135  134  133   
E   0  1  4  3  2  1  1   4   3   2 ...   142  141  140  139  138  137  136   
G   0  0  3  6  5  4  3   3   2   1 ...   145  144  143  142  141  140  139   
T   0  0  2  5  4  3  2   2   1   0 ...   148  147  146  145  144  143  142   
V   0  0  1  4  3  2  5   4   3   2 ...   151  150  149  148  147  146  145   
A   0  0  0  3  2  5  4   3   6   5 ...   154  153  152  151  150  149  148   
P   0  0  0  2  1  4  3   2   5   4 ...   157  156  155  154  153  152  151   
E   0  0  2  1  4  3  2   5   4   3 ...   160  159  158  157  156  155  154   
A   0  0  1  0  3  6  5   4   7   6 ...   163  162  161  160  159  158  157   
E   0  0  2  1  2  5  4   7   6   5 ...   166  165  164  163  162  161  160   
A   0  0  1  0  1  4  3   6   9   8 ...   169  168  167  166  165  164  163   
A   0  0  0  0  0  3  2   5   8   7 ...   172  171  170  

#### Same matrix as above but with numbers in each row and column, in order to find the position of the highest value.

In [48]:
table_new = pd.DataFrame(np.array(matrix(sequence_aa_homo, sequence_aa_mus)))

table_new

0    1    2    3    4    5    6    7    8    9   ...   91   92   93   \
0      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
1      0    2    1    0    0    0    0    0    0    0 ...     0    0    0   
2      0    1    4    3    2    1    0    2    1    0 ...     0    0    0   
3      0    0    3    6    5    4    3    2    1    0 ...     0    0    0   
4      0    0    2    5    4    3    2    1    0    0 ...     2    2    1   
5      0    0    1    4    3    6    5    4    3    2 ...     1    1    0   
6      0    0    0    3    2    5    8    7    6    5 ...     3    2    1   
7      0    0    2    2    5    4    7   10    9    8 ...     2    1    0   
8      0    0    1    1    4    7    6    9   12   11 ...     2    1    0   
9      0    0    0    0    3    6    5    8   11   14 ...     1    0    0   
10     0    0    0    0    2    5    8    7   10   13 ...     4    3    2   
11     0    0    2    1    2    4    7   10    9   12 ...     3    2    1   
12     0    0    2    1    3    3    6    9    8   11 ...     2    1    0   
13     0    0    1    0    2    2    5    8    7   10 ...     1    0    0   
14     0    0    2    1    2    1    4    7    6    9 ...     0    0    0   
15     0    0    1    0    1    0    3    6    5    8 ...     0    0    2   
16     0    0    0    0    0    0    2    5    4    7 ...     0    0    1   
17     0    0    0    0    0    0    1    4    3    6 ...     0    0    0   
18     0    0    0    0    0    0    0    3    2    5 ...     0    0    0   
19     0    0    0    2    1    0    0    2    1    4 ...     0    0    0   
20     0    0    0    1    0    0    0    1    0    3 ...     0    0    0   
21     0    0    2    1    3    2    1    2    1    2 ...     0    0    0   
22     0    0    1    0    2    1    0    1    0    1 ...     0    0    0   
23     0    0    0    0    1    0    0    0    0    0 ...     0    0    0   
24     0    0    0    0    0    0    0    0    0    0 ...     0    0    2   
25     0    0    0    0    0    0    0    0    0    0 ...     0    0    1   
26     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
27     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
28     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
29     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
71     0    0    0    0    0    0    0    0    0    0 ...   118  117  116   
72     0    0    0    0    0    0    0    0    0    0 ...   121  120  119   
73     0    2    1    0    0    0    0    0    0    0 ...   124  123  122   
74     0    1    0    0    0    0    0    0    0    0 ...   127  126  125   
75     0    0    0    0    0    0    0    0    0    0 ...   130  129  128   
76     0    0    2    1    2    1    0    2    1    0 ...   133  132  131   
77     0    0    1    0    1    0    3    2    1    0 ...   136  135  134   
78     0    2    1    0    0    0    2    1    0    0 ...   139  138  137   
79     0    1    4    3    2    1    1    4    3    2 ...   142  141  140   
80     0    0    3    6    5    4    3    3    2    1 ...   145  144  143   
81     0    0    2    5    4    3    2    2    1    0 ...   148  147  146   
82     0    0    1    4    3    2    5    4    3    2 ...   151  150  149   
83     0    0    0    3    2    5    4    3    6    5 ...   154  153  152   
84     0    0    0    2    1    4    3    2    5    4 ...   157  156  155   
85     0    0    2    1    4    3    2    5    4    3 ...   160  159  158   
86     0    0    1    0    3    6    5    4    7    6 ...   163  162  161   
87     0    0    2    1    2    5    4    7    6    5 ...   166  165  164   
88     0    0    1    0    1    4    3    6    9    8 ...   169  168  167   
89     0    0    0    0    0    3    2    5    8    7 ...   172  171  170   
90     0    0    0    0    0    2    5    4    7    6 ...   175  174  173   
9

#### The highest value:

In [49]:
max_Value = max(table_new.max())
max_Value

196

#### X and Y position of the highest value:

In [50]:
xpos=-1
ypos=-1
for i in range(101):
    for j in range(101):
        if (table_new[i][j]==max_Value):
            xpos=i
            ypos=j
            break
        
if (xpos==-1|ypos==-1):
    print("Something went wrong")
    
print("X position:", xpos,"\nY position:", ypos)

X position: 100 
Y position: 100


## Part 4

### Using the datasets from part 2, implement your own Smith-Waterman Algorithm for global alignment of the Amino Acid sequences that will score the identical and substitutions based on the BLOSUM62 scoring matrix (tab delimeted file). For gap penalty use -10. Print the final scoring matrix and find the position of the highest value.

#### Read the BLOSUM62.txt file

In [51]:
blosum62 = pd.read_csv("http://139.91.190.186/tei/bioinformatics/exercise2/BLOSUM62.txt", sep="\t")

#### Final scoring matrix using Smith-Waterman Algorithm:

In [52]:
def matrix_new(a, b, gap_cost=10):
    H = np.zeros((len(a) + 1, len(b) + 1), np.int)

    for i in range(1, H.shape[0]):
        for j in range(1, H.shape[1]):
            temp = blosum62.columns.get_loc(b[i-1])
            #print("temp=",temp)
            #print("a[j - 1] =",a[j - 1])
            #print("b[i-1]=",b[i-1])
            #print("blosum62[a[j - 1]][temp]=",blosum62[a[j - 1]][temp-1])
            #print("blosum62['Μ'][13]=",blosum62['Μ'][13])
            match = H[i - 1, j - 1] + (blosum62[a[j - 1]][temp])
            delete = H[i - 1, j] - gap_cost
            insert = H[i, j - 1] - gap_cost
            H[i, j] = max(match, delete, insert, 0)
    return H
    
print(matrix_new(sequence_aa_homo, sequence_aa_mus))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 2 1 0]
 [0 0 5 ... 0 4 0]
 [0 0 1 ... 0 0 1]]


#### New final scoring matrix. (With the proper indexes for rows and columns)

In [53]:
arr_seq_aa_mus = list(sequence_aa_mus)
arr_seq_aa_mus.insert(0," ")

table2 = pd.DataFrame(np.array(matrix_new(sequence_aa_homo, sequence_aa_mus)),
                   columns=arr_seq_aa_mus)

table2.index = arr_seq_aa_homo
table

M  E  G  E  A  V   E   A   I ...     D    D    T    Q    I    I    T  \
    0  0  0  0  0  0  0   0   0   0 ...     0    0    0    0    0    0    0   
M   0  2  1  0  0  0  0   0   0   0 ...     0    0    0    0    0    0    0   
E   0  1  4  3  2  1  0   2   1   0 ...     0    0    0    0    0    0    0   
G   0  0  3  6  5  4  3   2   1   0 ...     0    0    0    0    0    0    0   
D   0  0  2  5  4  3  2   1   0   0 ...     2    2    1    0    0    0    0   
A   0  0  1  4  3  6  5   4   3   2 ...     1    1    0    0    0    0    0   
V   0  0  0  3  2  5  8   7   6   5 ...     3    2    1    0    0    0    0   
E   0  0  2  2  5  4  7  10   9   8 ...     2    1    0    0    0    0    0   
A   0  0  1  1  4  7  6   9  12  11 ...     2    1    0    0    0    0    0   
I   0  0  0  0  3  6  5   8  11  14 ...     1    0    0    0    2    2    1   
V   0  0  0  0  2  5  8   7  10  13 ...     4    3    2    1    1    1    0   
E   0  0  2  1  2  4  7  10   9  12 ...     3    2    1    0    0    0    0   
E   0  0  2  1  3  3  6   9   8  11 ...     2    1    0    0    0    0    0   
S   0  0  1  0  2  2  5   8   7  10 ...     1    0    0    0    0    0    0   
E   0  0  2  1  2  1  4   7   6   9 ...     0    0    0    0    0    0    0   
T   0  0  1  0  1  0  3   6   5   8 ...     0    0    2    1    0    0    2   
F   0  0  0  0  0  0  2   5   4   7 ...     0    0    1    0    0    0    1   
I   0  0  0  0  0  0  1   4   3   6 ...     0    0    0    0    2    2    1   
K   0  0  0  0  0  0  0   3   2   5 ...     0    0    0    0    1    1    0   
G   0  0  0  2  1  0  0   2   1   4 ...     0    0    0    0    0    0    0   
K   0  0  0  1  0  0  0   1   0   3 ...     0    0    0    0    0    0    0   
E   0  0  2  1  3  2  1   2   1   2 ...     0    0    0    0    0    0    0   
R   0  0  1  0  2  1  0   1   0   1 ...     0    0    0    0    0    0    0   
K   0  0  0  0  1  0  0   0   0   0 ...     0    0    0    0    0    0    0   
T   0  0  0  0  0  0  0   0   0   0 ...     0    0    2    1    0    0    2   
Y   0  0  0  0  0  0  0   0   0   0 ...     0    0    1    0    0    0    1   
Q   0  0  0  0  0  0  0   0   0   0 ...     0    0    0    3    2    1    0   
R   0  0  0  0  0  0  0   0   0   0 ...     0    0    0    2    1    0    0   
R   0  0  0  0  0  0  0   0   0   0 ...     0    0    0    1    0    0    0   
R   0  0  0  0  0  0  0   0   0   0 ...     0    0    0    0    0    0    0   
.. .. .. .. .. .. .. ..  ..  ..  .. ...   ...  ...  ...  ...  ...  ...  ...   
L   0  0  0  0  0  0  0   0   0   0 ...   118  117  116  115  114  113  112   
Q   0  0  0  0  0  0  0   0   0   0 ...   121  120  119  118  117  116  115   
M   0  2  1  0  0  0  0   0   0   0 ...   124  123  122  121  120  119  118   
K   0  1  0  0  0  0  0   0   0   0 ...   127  126  125  124  123  122  121   
T   0  0  0  0  0  0  0   0   0   0 ...   130  129  128  127  126  125  124   
E   0  0  2  1  2  1  0   2   1   0 ...   133  132  131  130  129  128  127   
V   0  0  1  0  1  0  3   2   1   0 ...   136  135  134  133  132  131  130   
M   0  2  1  0  0  0  2   1   0   0 ...   139  138  137  136  135  134  133   
E   0  1  4  3  2  1  1   4   3   2 ...   142  141  140  139  138  137  136   
G   0  0  3  6  5  4  3   3   2   1 ...   145  144  143  142  141  140  139   
T   0  0  2  5  4  3  2   2   1   0 ...   148  147  146  145  144  143  142   
V   0  0  1  4  3  2  5   4   3   2 ...   151  150  149  148  147  146  145   
A   0  0  0  3  2  5  4   3   6   5 ...   154  153  152  151  150  149  148   
P   0  0  0  2  1  4  3   2   5   4 ...   157  156  155  154  153  152  151   
E   0  0  2  1  4  3  2   5   4   3 ...   160  159  158  157  156  155  154   
A   0  0  1  0  3  6  5   4   7   6 ...   163  162  161  160  159  158  157   
E   0  0  2  1  2  5  4   7   6   5 ...   166  165  164  163  162  161  160   
A   0  0  1  0  1  4  3   6   9   8 ...   169  168  167  166  165  164  163   
A   0  0  0  0  0  3  2   5   8   7 ...   172  171  170  

#### The same matrix as the one above but with numbers as indexes.

In [54]:
table_new2 = pd.DataFrame(np.array(matrix_new(sequence_aa_homo, sequence_aa_mus)))
table_new2

0    1    2    3    4    5    6    7    8    9   ...   91   92   93   \
0      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
1      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
2      0    0    0    6    0    0    0    0    0    0 ...     0    0    0   
3      0    0    0    0    5    0    0    0    0    0 ...     0    0    0   
4      0    0    0    6    0    5    0    0    0    0 ...     0    0    0   
5      0    0    0    0    4    0    2    0    0    0 ...     0    0    0   
6      0    0    1    0    4    2    0    3    0    0 ...     4    4    0   
7      0    0    0    7    0    4    0    0    3    0 ...     0    3    2   
8      0    0    0    0    5    0    1    0    0    0 ...     0    0    2   
9      0    2    0    0    0    4    1    0    0    2 ...     0    0    0   
10     0    0    3    0    4    0    1    2    0    0 ...     5    4    0   
11     0    0    0    9    0    4    0    0    2    0 ...     0    4    2   
12     0    0    0    6    8    0    1    0    0    0 ...     0    0    2   
13     0    0    0    0    5    8    0    0    0    0 ...     0    0    5   
14     0    0    0    6    0    5    5    0    0    0 ...     0    0    0   
15     0    0    0    0    2    0    2    2    0    0 ...     0    0    0   
16     0    0    0    0    0    1    0    1    1    0 ...     0    0    0   
17     0    2    0    0    0    0    2    0    0    3 ...     0    0    0   
18     0    5    0    0    0    0    1    0    0    1 ...     0    0    0   
19     0    0    5    0    0    0    0    1    0    0 ...     0    0    0   
20     0    5    0    2    0    0    1    0    0    1 ...     0    0    0   
21     0    0    3    6    1    0    0    0    0    0 ...     0    0    0   
22     0    0    0    3    7    0    0    0    0    0 ...     1    1    0   
23     0    5    0    0    0    6    1    0    0    1 ...     1    0    0   
24     0    0    2    0    0    0    3    0    0    0 ...     0    0    0   
25     0    1    0    0    0    0    4    1    0    3 ...     0    0    0   
26     0    0    6    0    2    0    0    9    0    0 ...     6    2    0   
27     0    0    0    6    1    0    0    0    7    0 ...     1    7    2   
28     0    0    0    0    7    0    0    0    0    4 ...     1    2    7   
29     0    0    0    0    1    5    0    0    0    0 ...     1    2    2   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
71     0    0    1    0    0    0    0    1    0    0 ...     0    0    0   
72     0    0    5    0    2    0    0    5    0    0 ...     2    2    0   
73     0    0    0    2    0    0    0    0    3    0 ...     0    0    0   
74     0    5    0    0    0    0    1    0    0    4 ...     0    0    0   
75     0    0    2    0    0    0    0    0    0    0 ...     0    0    0   
76     0    0    0    8    0    0    0    0    0    0 ...     0    0    0   
77     0    0    1    0   12    2    0    1    0    0 ...     4    4    0   
78     0    0    0    0    2   10    1    0    0    0 ...     0    1    2   
79     0    0    0    6    0    2    7    0    0    0 ...     0    0    0   
80     0    0    0    0    5    0    0    7    0    0 ...     0    0    0   
81     0    0    0    0    0    2    0    0    4    0 ...     0    0    0   
82     0    0    1    0    4    0    0    1    0    1 ...     4    4    0   
83     0    0    0    0    0    3    0    0    0    0 ...     0    2    3   
84     0    0    0    0    0    1    1    0    1    0 ...     0    0    3   
85     0    0    0    6    0    0    0    0    0    0 ...     0    0    0   
86     0    0    0    0    4    0    0    0    0    0 ...     0    0    0   
87     0    0    0    6    0    4    0    0    0    0 ...     4    0    0   
88     0    0    0    0    4    0    1    0    0    0 ...     0    2    0   
89     0    0    0    0    0    3    0    1    0    0 ...     0    0    1   
90     0    0    1    0    4    0    0    1    0    0 ...     4    4    0   
9

#### Highest value:

In [55]:
max_Value2 = max(table_new2.max())
max_Value2

27

In [56]:
xpos2=-1
ypos2=-1
for i in range(101):
    for j in range(101):
        if (table_new2[i][j]==max_Value2):
            xpos2=i
            ypos2=j
            break
        
if (xpos2|ypos2==-1):
    print("Something went wrong")
    
print("X position:", xpos2,"\nY position:", ypos2)

X position: 46 
Y position: 54
